### ISSUE TITLE
Wrong version of nlogger in go.mod

### ISSUE THREAD

**Issue by walez** [lalamove/konfig#33]
Using version *v0.4.0* of konfig in a go module enabled project fails with *undefined: nlogger.Provider*

Checking version *0.4.0*'s go.mod I can see that version *v.0.0.2* of [nlogger](https://github.com/lalamove/nui/) is stated there but the *Provider* type was not introduced till *v0.0.4*.

I manually fixed it by specifying *v0.0.4* in my go.mod file but Konfig's go.mod will also need to be updated, I will trying submitting a PR for that.

Thanks for the awesome package.

**Comment by mikn** [comment]
Should be fixed by #34 . Thank you!
